# Generated by Django 5.1 on 2024-08-21 14:12

from django.db import migrations


def create_categories_data(apps, schema_editor):
    Category = apps.get_model("briefing_api", "Category")
    categories = ["Novo Produto", "Troca de Fornecedor", "Reformulação de Produto"]
    for name in categories:
        Category.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("briefing_api", "0002_alter_category_description"),
    ]

    operations = [migrations.RunPython(create_categories_data)]
