from django.urls import path
from . import views

urlpatterns = [
    path(
        "categories",
        views.CategoryListAPIView.as_view(),
        name="category-list",
    ),
    path(
        "category/<int:pk>/",
        views.CategoryRetrieveUpdateAPIView.as_view(),
        name="category-retrieve-update",
    ),
    path(
        "category/",
        views.CategoryCreateAPIView.as_view(),
        name="category-create",
    ),
    path(
        "vendors/",
        views.VendorListAPIView.as_view(),
        name="vendor-list",
    ),
    path(
        "vendor/<int:pk>/",
        views.VendorRetrieveUpdateAPIView.as_view(),
        name="vendor-retrieve-update",
    ),
    path(
        "vendor/",
        views.VendorCreateAPIView.as_view(),
        name="vendor-create",
    ),
    path(
        "retailers/",
        views.RetailerListAPIView.as_view(),
        name="retailer-list",
    ),
    path(
        "retailer/<int:pk>/",
        views.RetailerRetrieveUpdateAPIView.as_view(),
        name="retailer-retrieve-update",
    ),
    path(
        "retailer/",
        views.RetailerCreateAPIView.as_view(),
        name="retailer-create",
    ),
]
